version: '3'
services:
  app:
    build: .
    container_name: app
    restart: always
    # we can see the server running at "localhost:8080"
    ports:
      - "8080:80"

  e2e:
    build: .
    container_name: end-to-end
    depends_on:
      - app
    command: npx cypress run
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json
      - ./cypress.config.js:/cypress.config.js

