version: '3'
services:
  e2e:
    build: .
    container_name: end-to-end
    command: npx cypress run
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json
      - ./cypress.config.js:/cypress.config.js

